# Generated by Django 5.2 on 2026-06-29 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='完成订单数')),
                ('total_orders', models.IntegerField(default=0, verbose_name='总接单数')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='平均评分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL, verbose_name='技师')),
            ],
            options={
                'verbose_name': '技师绩效',
                'verbose_name_plural': '技师绩效管理',
                'ordering': ['-date'],
                'unique_together': {('technician', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TechnicianSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='上班时间')),
                ('end_time', models.TimeField(verbose_name='下班时间')),
                ('is_work_day', models.BooleanField(default=True, verbose_name='是否上班')),
                ('max_orders', models.IntegerField(default=10, verbose_name='最大接单量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='技师')),
            ],
            options={
                'verbose_name': '技师排班',
                'verbose_name_plural': '技师排班管理',
                'ordering': ['-date'],
                'unique_together': {('technician', 'date')},
            },
        ),
    ]
