# Generated by Django 5.2 on 2026-06-29 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宠物昵称')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='品种')),
                ('gender', models.CharField(blank=True, choices=[('male', '男孩子'), ('female', '女孩子')], max_length=10, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄(月)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='毛色')),
                ('size', models.CharField(choices=[('small', '小型'), ('medium', '中型'), ('large', '大型')], default='small', max_length=10, verbose_name='体型')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='宠物照片')),
                ('vaccination', models.TextField(blank=True, null=True, verbose_name='疫苗接种记录')),
                ('deworming', models.TextField(blank=True, null=True, verbose_name='驱虫记录')),
                ('allergies', models.TextField(blank=True, help_text='如皮肤过敏、食物过敏等', null=True, verbose_name='过敏史')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='既往病史')),
                ('taboos', models.TextField(blank=True, help_text='怕水、怕吹风机、攻击性强等', null=True, verbose_name='特殊禁忌')),
                ('personality', models.TextField(blank=True, null=True, verbose_name='宠物性格')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='洗护注意事项')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认宠物')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '宠物档案',
                'verbose_name_plural': '宠物档案管理',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
