# Generated by Django 5.2 on 2026-06-29 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期')),
                ('is_work_day', models.BooleanField(default=True, verbose_name='是否营业')),
                ('start_time', models.TimeField(default='09:00', verbose_name='开始时间')),
                ('end_time', models.TimeField(default='18:00', verbose_name='结束时间')),
                ('slot_interval', models.IntegerField(default=60, verbose_name='时段间隔(分钟)')),
                ('max_daily_bookings', models.IntegerField(default=50, verbose_name='每日最大预约量')),
            ],
            options={
                'verbose_name': '营业时间',
                'verbose_name_plural': '营业时间配置',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '服务分类',
                'verbose_name_plural': '服务分类管理',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('duration', models.IntegerField(default=60, verbose_name='服务时长(分钟)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='服务详情')),
                ('applicable_pets', models.CharField(blank=True, help_text='如：适合所有犬种/猫', max_length=200, null=True, verbose_name='适用宠物')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_photos/', verbose_name='服务图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='服务分类')),
            ],
            options={
                'verbose_name': '服务项目',
                'verbose_name_plural': '服务项目管理',
                'ordering': ['sort_order', 'category'],
            },
        ),
    ]
