# Generated by Django 5.2 on 2026-07-01

from django.db import migrations


def seed(apps, schema_editor):
    SC = apps.get_model('services', 'ServiceCategory')
    SI = apps.get_model('services', 'ServiceItem')
    BH = apps.get_model('services', 'BusinessHours')
    if SC.objects.exists():
        return
    c1 = SC.objects.create(name='基础洗护', icon='🛁', sort_order=1, is_active=True)
    c2 = SC.objects.create(name='深度护理', icon='🧴', sort_order=2, is_active=True)
    c3 = SC.objects.create(name='增值服务', icon='✨', sort_order=3, is_active=True)
    items = [
        [c1, '基础洗澡套餐', 68, 60, '包含全身水洗、香波护理、吹干、基础梳毛、耳部清洁', '适合所有小型犬/猫'],
        [c1, '标准洗护套餐', 98, 90, '包含基础洗澡+深度清洁+指甲修剪+苛门腺检查', '适合所有犬种/猫'],
        [c2, '深度洗护套餐', 168, 120, '包含标准洗护+去底绒+SPA护理+毛发养护', '适合中长毛犬种'],
        [c2, '驱虫洗护套餐', 128, 90, '包含标准洗护+体外驱虫药浴+环境驱虫咨询', '适合所有犬种/猫'],
        [c3, '毛发修剪', 88, 60, '专业造型修剪、打薄、修脚圆', '适合长毛犬种'],
        [c3, '指甲修剪+耳道清洁', 48, 30, '专业指甲修剪+耳道清理+脚底毛修剪', '适合所有宠物'],
    ]
    for cat, name, price, dur, desc, pets in items:
        SI.objects.create(category=cat, name=name, price=price, duration=dur, description=desc, applicable_pets=pets, is_active=True, sort_order=1)
    for d in range(7):
        BH.objects.create(day_of_week=d, is_work_day=(d != 6), start_time='09:00', end_time='18:00', slot_interval=60, max_daily_bookings=50)


class Migration(migrations.Migration):
    dependencies = [('services', '0001_initial')]
    operations = [
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
