# Generated by Django 5.2 on 2026-06-30 09:37

from django.db import migrations
from django.contrib.auth.hashers import make_password


def seed_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    
    # Only seed if no users exist (fresh database)
    if User.objects.exists():
        return
    
    users_data = [
        {'username': 'admin', 'password': 'admin123', 'role': 'admin', 'is_active': True, 'is_staff': True, 'is_superuser': True},
        {'username': 'tech1', 'password': 'tech123', 'role': 'technician', 'is_active': True},
        {'username': 'test', 'password': 'test123', 'role': 'customer', 'is_active': True},
    ]
    
    for data in users_data:
        password = data.pop('password')
        User.objects.create(**data, password=make_password(password))


def reverse_seed(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(username__in=['admin', 'tech1', 'test']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_users, reverse_seed),
    ]
