# Generated by Django 5.2 on 2026-06-29 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('appointment_time', models.TimeField(verbose_name='预约时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('pending_confirm', '待商家确认'), ('confirmed', '预约成功'), ('delayed', '订单延后'), ('in_progress', '洗护进行中'), ('pending_acceptance', '待验收'), ('completed', '已完成'), ('cancelled', '已取消'), ('locked', '已锁定')], default='pending_confirm', max_length=30, verbose_name='订单状态')),
                ('payment_method', models.CharField(choices=[('online', '线上预付'), ('store', '到店付款')], default='store', max_length=10, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='特殊备注')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='取消原因')),
                ('delay_reason', models.TextField(blank=True, null=True, verbose_name='延后原因')),
                ('delay_count', models.IntegerField(default=0, verbose_name='延后次数')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='驳回原因')),
                ('before_photos', models.ImageField(blank=True, null=True, upload_to='service_photos/', verbose_name='洗护前照片')),
                ('after_photos', models.ImageField(blank=True, null=True, upload_to='service_photos/', verbose_name='洗护后照片')),
                ('service_notes', models.TextField(blank=True, null=True, verbose_name='服务记录')),
                ('is_locked', models.BooleanField(default=False, verbose_name='是否锁定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_orders', to=settings.AUTH_USER_MODEL, verbose_name='锁定人')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet', verbose_name='宠物')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceitem', verbose_name='洗护服务')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='技师')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('created', '创建订单'), ('confirmed', '确认接单'), ('rejected', '驳回预约'), ('rescheduled', '改期'), ('delayed', '延后'), ('assigned', '指派技师'), ('reassigned', '更换技师'), ('started', '开始服务'), ('completed', '完成服务'), ('cancelled', '取消订单'), ('locked', '锁定订单'), ('unlocked', '解冻订单'), ('accepted', '验收完成')], max_length=30, verbose_name='操作类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='操作内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单操作日志',
                'verbose_name_plural': '订单操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
